-- codegen/Bundle.hs
-- Reads all *.simf files from std/src/ and produces two distribution bundles:
--   dist/mcpp/std.simf  — mcpp-compatible single file
--   dist/lib/std.simf   — same, with every fn prefixed with `pub`
-- Run via build.ps1 (after codegen/Main.hs has generated the source files).
module Main where

import Data.Char (isDigit)
import Data.List (isPrefixOf, sortBy)
import Data.Ord (comparing)
import System.Directory (createDirectoryIfMissing, doesFileExist, listDirectory)
import System.Exit (exitFailure)
import System.FilePath (takeExtension, takeBaseName)
import System.IO (hPutStrLn, stderr)

mcppHeader :: String
mcppHeader = unlines
  [ "// AUTO-GENERATED by codegen/Bundle.hs. DO NOT EDIT MANUALLY."
  , "// Run build.ps1 to regenerate."
  , ""
  , "// mcpp distribution: include this single file with the C preprocessor."
  , "// Example:  #include \"dist/mcpp/std.simf\""
  , ""
  , "#ifndef SIMP_STD_SIMF"
  , "#define SIMP_STD_SIMF"
  , ""
  ]

libHeader :: String
libHeader = unlines
  [ "// AUTO-GENERATED by codegen/Bundle.hs. DO NOT EDIT MANUALLY."
  , "// Run build.ps1 to regenerate."
  , ""
  , "// lib distribution: all functions exported as pub."
  , ""
  ]

mcppFooter :: String
mcppFooter = "\n#endif // SIMP_STD_SIMF\n"

-- | Sort key: lib first, uN by numeric width, types last, others alphabetically.
sortKey :: FilePath -> (Int, Int, FilePath)
sortKey f
  | f == "lib.simf"                         = (0, 0, f)
  | "u" `isPrefixOf` base, all isDigit rest = (1, read rest, f)
  | f == "types.simf"                       = (3, 0, f)
  | otherwise                               = (2, 0, f)
  where
    base = takeBaseName f
    rest = drop 1 base

-- | Prefix every top-level fn definition with `pub`.
addPub :: String -> String
addPub = unlines . map pubLine . lines
  where
    pubLine line
      | "fn " `isPrefixOf` line = "pub " ++ line
      | otherwise               = line

main :: IO ()
main = do
  createDirectoryIfMissing True "dist/mcpp"
  createDirectoryIfMissing True "dist/lib"

  allFiles <- listDirectory "std/src"
  let simfFiles = sortBy (comparing sortKey) $ filter ((== ".simf") . takeExtension) allFiles

  chunks <- mapM readSrc simfFiles
  let body = concat chunks

  writeFile "dist/mcpp/std.simf" (mcppHeader ++ body ++ mcppFooter)
  putStrLn $ "  wrote dist/mcpp/std.simf"

  writeFile "dist/lib/std.simf" (libHeader ++ addPub body)
  putStrLn $ "  wrote dist/lib/std.simf"

  putStrLn $ "  (" ++ show (length simfFiles) ++ " source files bundled)"

readSrc :: FilePath -> IO String
readSrc name = do
  let path = "std/src/" ++ name
  exists <- doesFileExist path
  if exists
    then readFile path
    else do
      hPutStrLn stderr $ "Missing source file: " ++ path
      exitFailure
