-- codegen/Main.hs
-- Run via: runghc codegen/Main.hs  (or via generate.ps1)
module Main where

import Data.List (intercalate, isPrefixOf)
import Control.Exception (catch, SomeException)
import System.Directory (createDirectoryIfMissing, doesFileExist, listDirectory, removeFile)

-- ---------------------------------------------------------------------------
-- Configuration: integer width types
-- ---------------------------------------------------------------------------

-- | Integer width configuration.
--   tcHasArith: add/subtract/multiply jets exist (u8–u64 only)
--   tcHasMul:   multiply jet exists (requires u(2N) result type)
data TypeConfig = TypeConfig
  { tcBits     :: Int
  , tcHasArith :: Bool
  , tcHasMul   :: Bool
  }

allTypes :: [TypeConfig]
allTypes =
  [ TypeConfig 8   True  True
  , TypeConfig 16  True  True
  , TypeConfig 32  True  True
  , TypeConfig 64  True  True
  , TypeConfig 128 False False  -- no arithmetic jets above u64
  , TypeConfig 256 False False
  ]

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

-- | Type name, e.g. "u32"
tn :: Int -> String
tn n = "u" ++ show n

-- | Width suffix, e.g. "32"
ws :: Int -> String
ws = show

autoGenHeader :: [String]
autoGenHeader =
  [ "// AUTO-GENERATED by codegen/Main.hs. DO NOT EDIT MANUALLY."
  , "// Run generate.ps1 to regenerate this file."
  , ""
  ]

block :: [String] -> String
block = unlines

-- ---------------------------------------------------------------------------
-- Integer width generators
-- ---------------------------------------------------------------------------

genAdd :: Int -> String
genAdd n = block
  [ "fn checked_add_" ++ ws n ++ "(a: " ++ tn n ++ ", b: " ++ tn n ++ ") -> Option<" ++ tn n ++ "> {"
  , "    let (carry, sum): (bool, " ++ tn n ++ ") = jet::add_" ++ ws n ++ "(a, b);"
  , "    match carry {"
  , "        true => None,"
  , "        false => Some(sum),"
  , "    }"
  , "}"
  , ""
  , "fn safe_add_" ++ ws n ++ "(a: " ++ tn n ++ ", b: " ++ tn n ++ ") -> " ++ tn n ++ " {"
  , "    unwrap(checked_add_" ++ ws n ++ "(a, b))"
  , "}"
  ]

genSub :: Int -> String
genSub n = block
  [ "fn checked_subtract_" ++ ws n ++ "(a: " ++ tn n ++ ", b: " ++ tn n ++ ") -> Option<" ++ tn n ++ "> {"
  , "    let (borrow, diff): (bool, " ++ tn n ++ ") = jet::subtract_" ++ ws n ++ "(a, b);"
  , "    match borrow {"
  , "        true => None,"
  , "        false => Some(diff),"
  , "    }"
  , "}"
  , ""
  , "fn safe_subtract_" ++ ws n ++ "(a: " ++ tn n ++ ", b: " ++ tn n ++ ") -> " ++ tn n ++ " {"
  , "    unwrap(checked_subtract_" ++ ws n ++ "(a, b))"
  , "}"
  ]

genMul :: Int -> String
genMul n = block
  [ "fn checked_multiply_" ++ ws n ++ "(a: " ++ tn n ++ ", b: " ++ tn n ++ ") -> Option<" ++ tn n ++ "> {"
  , "    let result: " ++ tn (n * 2) ++ " = jet::multiply_" ++ ws n ++ "(a, b);"
  , "    let (high, low): (" ++ tn n ++ ", " ++ tn n ++ ") = <" ++ tn (n * 2) ++ ">::into(result);"
  , "    match jet::is_zero_" ++ ws n ++ "(high) {"
  , "        true => Some(low),"
  , "        false => None,"
  , "    }"
  , "}"
  , ""
  , "fn safe_multiply_" ++ ws n ++ "(a: " ++ tn n ++ ", b: " ++ tn n ++ ") -> " ++ tn n ++ " {"
  , "    unwrap(checked_multiply_" ++ ws n ++ "(a, b))"
  , "}"
  ]

genSatAdd :: Int -> String
genSatAdd n = block
  [ "fn saturating_add_" ++ ws n ++ "(a: " ++ tn n ++ ", b: " ++ tn n ++ ") -> " ++ tn n ++ " {"
  , "    let (carry, sum): (bool, " ++ tn n ++ ") = jet::add_" ++ ws n ++ "(a, b);"
  , "    match carry {"
  , "        true => 0x" ++ replicate (n `div` 4) 'f' ++ ","
  , "        false => sum,"
  , "    }"
  , "}"
  ]

genEq :: TypeConfig -> String
genEq tc
  -- u8–u64: subtract then check if diff is zero
  | tcHasArith tc = block
      [ "fn eq_" ++ ws n ++ "(val1: " ++ tn n ++ ", val2: " ++ tn n ++ ") -> bool {"
      , "    let (borrow, diff): (bool, " ++ tn n ++ ") = jet::subtract_" ++ ws n ++ "(val1, val2);"
      , "    match borrow {"
      , "        true => false,"
      , "        false => jet::is_zero_" ++ ws n ++ "(diff),"
      , "    }"
      , "}"
      ]
  -- u128: zero-extend into u256 and use jet::eq_256
  | n == 128 = block
      [ "fn eq_" ++ ws n ++ "(val1: " ++ tn n ++ ", val2: " ++ tn n ++ ") -> bool {"
      , "    jet::eq_256(<(u128, u128)>::into((0, val1)), <(u128, u128)>::into((0, val2)))"
      , "}"
      ]
  -- u256: decompose into u128 halves and compare each with eq_128
  | otherwise = block
      [ "fn eq_" ++ ws n ++ "(val1: " ++ tn n ++ ", val2: " ++ tn n ++ ") -> bool {"
      , "    let (a_hi, a_lo): (u128, u128) = <u256>::into(val1);"
      , "    let (b_hi, b_lo): (u128, u128) = <u256>::into(val2);"
      , "    match eq_128(a_hi, b_hi) {"
      , "        true => eq_128(a_lo, b_lo),"
      , "        false => false,"
      , "    }"
      , "}"
      ]
  where n = tcBits tc

genAssertEq :: Int -> String
genAssertEq n = block
  [ "fn assert_eq" ++ ws n ++ "(a: " ++ tn n ++ ", b: " ++ tn n ++ ") {"
  , "    assert!(eq_" ++ ws n ++ "(a, b));"
  , "}"
  ]

genAssertNone :: Int -> String
genAssertNone n = block
  [ "fn assert_none" ++ ws n ++ "(val: Option<" ++ tn n ++ ">) {"
  , "    assert!(is_none::<" ++ tn n ++ ">(val));"
  , "}"
  ]

genAssertModule :: [TypeConfig] -> String
genAssertModule tcs = unlines autoGenHeader
  ++ intercalate "\n" (map (genAssertEq . tcBits) tcs)
  ++ "\n"
  ++ intercalate "\n" (map (genAssertNone . tcBits) tcs)

-- ---------------------------------------------------------------------------
-- Per-type module
-- ---------------------------------------------------------------------------

genTypeModule :: TypeConfig -> String
genTypeModule tc = unlines autoGenHeader ++ body
  where
    n    = tcBits tc
    ops  = (if tcHasArith tc then [genAdd n, genSub n] ++ [genMul n | tcHasMul tc] ++ [genSatAdd n] else []) ++ [genEq tc]
    body = intercalate "\n" ops

-- ---------------------------------------------------------------------------
-- Domain type algebra
-- ---------------------------------------------------------------------------

data Ty
  = TU Int          -- uN primitive
  | TRef String     -- named type reference: calls eq_Name
  | TPair Ty Ty     -- (A, B)
  | TEither Ty Ty   -- Either<A, B>
  | TArr8 Int       -- [u8; N], compared by splitting into two u(N*4) halves
  | TList Ty Int    -- List<T, N> — eq not yet supported

tyStr :: Ty -> String
tyStr (TU n)        = "u" ++ show n
tyStr (TRef name)   = name
tyStr (TPair a b)   = "(" ++ tyStr a ++ ", " ++ tyStr b ++ ")"
tyStr (TEither a b) = "Either<" ++ tyStr a ++ ", " ++ tyStr b ++ ">"
tyStr (TArr8 n)     = "[u8; " ++ show n ++ "]"
tyStr (TList t n)   = "List<" ++ tyStr t ++ ", " ++ show n ++ ">"

hasListType :: Ty -> Bool
hasListType (TList _ _)   = True
hasListType (TPair a b)   = hasListType a || hasListType b
hasListType (TEither a b) = hasListType a || hasListType b
hasListType _             = False

-- | Equality expression for use inside a match arm (single expression or block).
eqExpr :: Ty -> String -> String -> String
eqExpr (TU 1)      a b = "jet::eq_1(" ++ a ++ ", " ++ b ++ ")"
eqExpr (TU n)      a b = "eq_" ++ show n ++ "(" ++ a ++ ", " ++ b ++ ")"
eqExpr (TRef name) a b = "eq_" ++ name ++ "(" ++ a ++ ", " ++ b ++ ")"
eqExpr (TList _ _) _ _ = "false // TODO: List equality not yet implemented"
eqExpr (TArr8 n) a b =
  let halfBits = n * 8 `div` 2
      hTy      = "u" ++ show halfBits
  in "{\n" ++
     "            let (" ++ a ++ "_hi, " ++ a ++ "_lo): (" ++ hTy ++ ", " ++ hTy ++ ") = <[u8; " ++ show n ++ "]>::into(" ++ a ++ ");\n" ++
     "            let (" ++ b ++ "_hi, " ++ b ++ "_lo): (" ++ hTy ++ ", " ++ hTy ++ ") = <[u8; " ++ show n ++ "]>::into(" ++ b ++ ");\n" ++
     "            match eq_" ++ show halfBits ++ "(" ++ a ++ "_hi, " ++ b ++ "_hi) {\n" ++
     "                true => eq_" ++ show halfBits ++ "(" ++ a ++ "_lo, " ++ b ++ "_lo),\n" ++
     "                false => false,\n" ++
     "            }\n" ++
     "        }"
eqExpr (TPair t1 t2) a b =
  let pTy = "(" ++ tyStr t1 ++ ", " ++ tyStr t2 ++ ")"
      al = a ++ "_fst"; ar = a ++ "_snd"
      bl = b ++ "_fst"; br = b ++ "_snd"
  in "{\n" ++
     "            let (" ++ al ++ ", " ++ ar ++ "): " ++ pTy ++ " = <" ++ pTy ++ ">::into(" ++ a ++ ");\n" ++
     "            let (" ++ bl ++ ", " ++ br ++ "): " ++ pTy ++ " = <" ++ pTy ++ ">::into(" ++ b ++ ");\n" ++
     "            match " ++ eqExpr t1 al bl ++ " {\n" ++
     "                true => " ++ eqExpr t2 ar br ++ ",\n" ++
     "                false => false,\n" ++
     "            }\n" ++
     "        }"
eqExpr (TEither t1 t2) a b =
  "match " ++ a ++ " {\n" ++
  "            Left(" ++ a ++ "_i: " ++ tyStr t1 ++ ") => match " ++ b ++ " {\n" ++
  "                Left(" ++ b ++ "_i: " ++ tyStr t1 ++ ") => " ++ eqExpr t1 (a ++ "_i") (b ++ "_i") ++ ",\n" ++
  "                Right(_: " ++ tyStr t2 ++ ") => false,\n" ++
  "            },\n" ++
  "            Right(" ++ a ++ "_i: " ++ tyStr t2 ++ ") => match " ++ b ++ " {\n" ++
  "                Right(" ++ b ++ "_i: " ++ tyStr t2 ++ ") => " ++ eqExpr t2 (a ++ "_i") (b ++ "_i") ++ ",\n" ++
  "                Left(_: " ++ tyStr t1 ++ ") => false,\n" ++
  "            },\n" ++
  "        }"

-- | Equality body for the top level of a function (4-space indent).
eqBody :: Ty -> String -> String -> String
eqBody (TU 1)      a b = "jet::eq_1(" ++ a ++ ", " ++ b ++ ")"
eqBody (TU n)      a b = "eq_" ++ show n ++ "(" ++ a ++ ", " ++ b ++ ")"
eqBody (TRef name) a b = "eq_" ++ name ++ "(" ++ a ++ ", " ++ b ++ ")"
eqBody (TList _ _) _ _ = "false // TODO: List equality not yet implemented"
eqBody (TArr8 n) a b =
  let halfBits = n * 8 `div` 2
      hTy      = "u" ++ show halfBits
  in "let (" ++ a ++ "_hi, " ++ a ++ "_lo): (" ++ hTy ++ ", " ++ hTy ++ ") = <[u8; " ++ show n ++ "]>::into(" ++ a ++ ");\n" ++
     "    let (" ++ b ++ "_hi, " ++ b ++ "_lo): (" ++ hTy ++ ", " ++ hTy ++ ") = <[u8; " ++ show n ++ "]>::into(" ++ b ++ ");\n" ++
     "    match eq_" ++ show halfBits ++ "(" ++ a ++ "_hi, " ++ b ++ "_hi) {\n" ++
     "        true => eq_" ++ show halfBits ++ "(" ++ a ++ "_lo, " ++ b ++ "_lo),\n" ++
     "        false => false,\n" ++
     "    }"
eqBody (TPair t1 t2) a b =
  let pTy = "(" ++ tyStr t1 ++ ", " ++ tyStr t2 ++ ")"
      al = a ++ "_fst"; ar = a ++ "_snd"
      bl = b ++ "_fst"; br = b ++ "_snd"
  in "let (" ++ al ++ ", " ++ ar ++ "): " ++ pTy ++ " = <" ++ pTy ++ ">::into(" ++ a ++ ");\n" ++
     "    let (" ++ bl ++ ", " ++ br ++ "): " ++ pTy ++ " = <" ++ pTy ++ ">::into(" ++ b ++ ");\n" ++
     "    match " ++ eqExpr t1 al bl ++ " {\n" ++
     "        true => " ++ eqExpr t2 ar br ++ ",\n" ++
     "        false => false,\n" ++
     "    }"
eqBody (TEither t1 t2) a b =
  "match " ++ a ++ " {\n" ++
  "        Left(" ++ a ++ "_i: " ++ tyStr t1 ++ ") => match " ++ b ++ " {\n" ++
  "            Left(" ++ b ++ "_i: " ++ tyStr t1 ++ ") => " ++ eqExpr t1 (a ++ "_i") (b ++ "_i") ++ ",\n" ++
  "            Right(_: " ++ tyStr t2 ++ ") => false,\n" ++
  "        },\n" ++
  "        Right(" ++ a ++ "_i: " ++ tyStr t2 ++ ") => match " ++ b ++ " {\n" ++
  "            Right(" ++ b ++ "_i: " ++ tyStr t2 ++ ") => " ++ eqExpr t2 (a ++ "_i") (b ++ "_i") ++ ",\n" ++
  "            Left(_: " ++ tyStr t1 ++ ") => false,\n" ++
  "        },\n" ++
  "    }"

genDomainEq :: String -> Ty -> String
genDomainEq name ty = block $
  if hasListType ty
    then
      [ "fn eq_" ++ name ++ "(_a: " ++ name ++ ", _b: " ++ name ++ ") -> bool {"
      , "    false // TODO: " ++ name ++ " involves List; equality not yet implemented"
      , "}"
      ]
    else
      let rawTy = tyStr ty
      in [ "fn eq_" ++ name ++ "(a: " ++ name ++ ", b: " ++ name ++ ") -> bool {"
         , "    let a_i: " ++ rawTy ++ " = <" ++ rawTy ++ ">::into(a);"
         , "    let b_i: " ++ rawTy ++ " = <" ++ rawTy ++ ">::into(b);"
         , "    " ++ eqBody ty "a_i" "b_i"
         , "}"
         ]

-- | Ordered so dependencies come before dependents.
domainTypes :: [(String, Ty)]
domainTypes =
  [ ("Confidential1", TPair (TU 1) (TU 256))
  , ("Point",         TPair (TU 1) (TU 256))
  , ("Ge",            TPair (TU 256) (TU 256))
  , ("Outpoint",      TPair (TU 256) (TU 32))
  , ("Gej",           TPair (TRef "Ge") (TU 256))
  , ("Amount1",       TEither (TRef "Point") (TU 64))
  , ("Asset1",        TEither (TRef "Point") (TU 256))
  , ("Nonce",         TEither (TRef "Point") (TU 256))
  , ("TokenAmount1",  TEither (TRef "Point") (TU 64))
  , ("Distance",      TU 16)
  , ("Duration",      TU 16)
  , ("ExplicitAmount",TU 64)
  , ("ExplicitAsset", TU 256)
  , ("ExplicitNonce", TU 256)
  , ("Fe",            TU 256)
  , ("Height",        TU 32)
  , ("Lock",          TU 32)
  , ("Message",       TU 256)
  , ("Message64",     TArr8 64)
  , ("Pubkey",        TU 256)
  , ("Scalar",        TU 256)
  , ("Signature",     TArr8 64)
  , ("Time",          TU 32)
  , ("Ctx8",          TPair (TList (TU 8) 64) (TPair (TU 64) (TU 256)))
  ]

genDomainAssertEq :: String -> Ty -> String
genDomainAssertEq name _ = block
  [ "fn assert_eq_" ++ name ++ "(a: " ++ name ++ ", b: " ++ name ++ ") {"
  , "    assert!(eq_" ++ name ++ "(a, b));"
  , "}"
  ]

genDomainAssertNone :: String -> Ty -> String
genDomainAssertNone name _ = block
  [ "fn assert_none_" ++ name ++ "(val: Option<" ++ name ++ ">) {"
  , "    assert!(is_none::<" ++ name ++ ">(val));"
  , "}"
  ]

genTypesModule :: [(String, Ty)] -> String
genTypesModule types = unlines autoGenHeader
  ++ intercalate "\n" (map (uncurry genDomainEq) types)
  ++ "\n"
  ++ intercalate "\n" (map (uncurry genDomainAssertEq) types)
  ++ "\n"
  ++ intercalate "\n" (map (uncurry genDomainAssertNone) types)

-- ---------------------------------------------------------------------------
-- IO helpers
-- ---------------------------------------------------------------------------

emit :: FilePath -> String -> IO ()
emit path content = do
  writeFile path content
  putStrLn $ "  wrote " ++ path

-- ---------------------------------------------------------------------------
-- Main
-- ---------------------------------------------------------------------------

-- | Remove stale uN.simf files for widths no longer in allTypes.
cleanStaleSrc :: IO ()
cleanStaleSrc = do
  let activeFiles = map (\tc -> tn (tcBits tc) ++ ".simf") allTypes
  existing <- listDirectory "std/src"
  let stale = filter (\f -> "u" `isPrefixOf` f && f `notElem` activeFiles) existing
  mapM_ (\f -> do
    let path = "std/src/" ++ f
    removeFile path `catch` (\(_ :: SomeException) -> return ())
    putStrLn $ "  removed stale " ++ path) stale

main :: IO ()
main = do
  createDirectoryIfMissing True "std/src"

  putStrLn "Cleaning stale source files..."
  cleanStaleSrc

  putStrLn "Generating per-type source modules..."
  mapM_ (\tc -> emit ("std/src/" ++ tn (tcBits tc) ++ ".simf") (genTypeModule tc)) allTypes

  putStrLn "Generating assert functions..."
  emit "std/src/assert.simf" (genAssertModule allTypes)

  putStrLn "Generating domain type eq functions..."
  emit "std/src/types.simf" (genTypesModule domainTypes)

  putStrLn "\nDone."
