-- codegen/Main.hs
-- Run via: runghc codegen/Main.hs  (or via generate.ps1)
module Main where

import Data.List (intercalate)
import System.Directory (createDirectoryIfMissing)

-- ---------------------------------------------------------------------------
-- Configuration: integer width types
-- ---------------------------------------------------------------------------

-- | Each integer width and which 2x-wide jets are available.
--   tcHasMul:   jet::multiply_N exists (requires u(2N) result type)
--   tcHasEqJet: jet::eq_(2N) exists (used for zero-extension equality trick)
data TypeConfig = TypeConfig
  { tcBits      :: Int
  , tcHasMul    :: Bool
  , tcHasEqJet  :: Bool
  }

allTypes :: [TypeConfig]
allTypes =
  [ TypeConfig 4   True  True
  , TypeConfig 8   True  True
  , TypeConfig 16  True  True
  , TypeConfig 32  True  True
  , TypeConfig 64  True  True
  , TypeConfig 128 False True   -- no u256 multiply jet; jet::eq_256 exists
  , TypeConfig 256 False False  -- no u512 for multiply or eq
  ]

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

-- | Type name, e.g. "u32"
tn :: Int -> String
tn n = "u" ++ show n

-- | Width suffix, e.g. "32"
ws :: Int -> String
ws = show

autoGenHeader :: [String]
autoGenHeader =
  [ "// AUTO-GENERATED by codegen/Main.hs. DO NOT EDIT MANUALLY."
  , "// Run generate.ps1 to regenerate this file."
  , ""
  ]

block :: [String] -> String
block = unlines

-- ---------------------------------------------------------------------------
-- Integer width generators
-- ---------------------------------------------------------------------------

genAdd :: Int -> String
genAdd n = block
  [ "fn safe_add_" ++ ws n ++ "(a: " ++ tn n ++ ", b: " ++ tn n ++ ") -> " ++ tn n ++ " {"
  , "    unwrap(checked_add_" ++ ws n ++ "(a, b))"
  , "}"
  , ""
  , "fn checked_add_" ++ ws n ++ "(a: " ++ tn n ++ ", b: " ++ tn n ++ ") -> Option<" ++ tn n ++ "> {"
  , "    let (carry, sum): (bool, " ++ tn n ++ ") = jet::add_" ++ ws n ++ "(a, b);"
  , "    match jet::eq_1(carry, 1) {"
  , "        true => Some(sum),"
  , "        false => None,"
  , "    }"
  , "}"
  ]

genSub :: Int -> String
genSub n = block
  [ "fn safe_sub_" ++ ws n ++ "(a: " ++ tn n ++ ", b: " ++ tn n ++ ") -> " ++ tn n ++ " {"
  , "    unwrap(checked_sub_" ++ ws n ++ "(a, b))"
  , "}"
  , ""
  , "fn checked_sub_" ++ ws n ++ "(a: " ++ tn n ++ ", b: " ++ tn n ++ ") -> Option<" ++ tn n ++ "> {"
  , "    let (borrow, diff): (bool, " ++ tn n ++ ") = jet::subtract_" ++ ws n ++ "(a, b);"
  , "    match jet::eq_1(borrow) {"
  , "        true => None,"
  , "        false => Some(diff),"
  , "    }"
  , "}"
  ]

genMul :: Int -> String
genMul n = block
  [ "fn safe_multiply_" ++ ws n ++ "(a: " ++ tn n ++ ", b: " ++ tn n ++ ") -> " ++ tn n ++ " {"
  , "    unwrap(checked_multiply_" ++ ws n ++ "(a, b))"
  , "}"
  , ""
  , "fn checked_multiply_" ++ ws n ++ "(a: " ++ tn n ++ ", b: " ++ tn n ++ ") -> Option<" ++ tn n ++ "> {"
  , "    let result: " ++ tn (n * 2) ++ " = jet::multiply_" ++ ws n ++ "(a, b);"
  , "    let (high, low): (" ++ tn n ++ ", " ++ tn n ++ ") = <" ++ tn (n * 2) ++ ">::into(result);"
  , "    match jet::is_zero_" ++ ws n ++ "(high) {"
  , "        true => Some(low),"
  , "        false => None,"
  , "    }"
  , "}"
  ]

genSatAdd :: Int -> String
genSatAdd n = block
  [ "fn saturating_add_" ++ ws n ++ "(a: " ++ tn n ++ ", b: " ++ tn n ++ ") -> " ++ tn n ++ " {"
  , "    let (carry, sum): (bool, " ++ tn n ++ ") = jet::add_" ++ ws n ++ "(a, b);"
  , "    match jet::eq_1(carry, 1) {"
  , "        true => sum,"
  , "        false => 0x" ++ replicate (n `div` 4) 'f' ++ ","
  , "    }"
  , "}"
  ]

genEq :: TypeConfig -> String
genEq tc
  | tcHasEqJet tc = block
      [ "fn eq_" ++ ws n ++ "(val1: " ++ tn n ++ ", val2: " ++ tn n ++ ") -> bool {"
      , "    jet::eq_" ++ ws (n * 2) ++ "(<(" ++ tn n ++ ", " ++ tn n ++ ")>::into((0, val1)), <(" ++ tn n ++ ", " ++ tn n ++ ")>::into((0, val2)))"
      , "}"
      ]
  | otherwise = block
      [ "fn eq_" ++ ws n ++ "(val1: " ++ tn n ++ ", val2: " ++ tn n ++ ") -> bool {"
      , "    let (a_hi, a_lo): (" ++ tn h ++ ", " ++ tn h ++ ") = <" ++ tn n ++ ">::into(val1);"
      , "    let (b_hi, b_lo): (" ++ tn h ++ ", " ++ tn h ++ ") = <" ++ tn n ++ ">::into(val2);"
      , "    match eq_" ++ ws h ++ "(a_hi, b_hi) {"
      , "        true => eq_" ++ ws h ++ "(a_lo, b_lo),"
      , "        false => false,"
      , "    }"
      , "}"
      ]
  where
    n = tcBits tc
    h = n `div` 2

-- ---------------------------------------------------------------------------
-- Per-type module
-- ---------------------------------------------------------------------------

genTypeModule :: TypeConfig -> String
genTypeModule tc = unlines autoGenHeader ++ body
  where
    n    = tcBits tc
    ops  = [genAdd n, genSub n] ++ [genMul n | tcHasMul tc] ++ [genSatAdd n, genEq tc]
    body = intercalate "\n" ops

-- ---------------------------------------------------------------------------
-- Domain type algebra
-- ---------------------------------------------------------------------------

data Ty
  = TU Int          -- uN primitive
  | TRef String     -- named type reference: calls eq_Name
  | TPair Ty Ty     -- (A, B)
  | TEither Ty Ty   -- Either<A, B>
  | TArr8 Int       -- [u8; N], compared by splitting into two u(N*4) halves
  | TList Ty Int    -- List<T, N> — eq not yet supported

tyStr :: Ty -> String
tyStr (TU n)        = "u" ++ show n
tyStr (TRef name)   = name
tyStr (TPair a b)   = "(" ++ tyStr a ++ ", " ++ tyStr b ++ ")"
tyStr (TEither a b) = "Either<" ++ tyStr a ++ ", " ++ tyStr b ++ ">"
tyStr (TArr8 n)     = "[u8; " ++ show n ++ "]"
tyStr (TList t n)   = "List<" ++ tyStr t ++ ", " ++ show n ++ ">"

hasListType :: Ty -> Bool
hasListType (TList _ _)   = True
hasListType (TPair a b)   = hasListType a || hasListType b
hasListType (TEither a b) = hasListType a || hasListType b
hasListType _             = False

-- | Equality expression for use inside a match arm (single expression or block).
eqExpr :: Ty -> String -> String -> String
eqExpr (TU 1)      a b = "jet::eq_1(" ++ a ++ ", " ++ b ++ ")"
eqExpr (TU n)      a b = "eq_" ++ show n ++ "(" ++ a ++ ", " ++ b ++ ")"
eqExpr (TRef name) a b = "eq_" ++ name ++ "(" ++ a ++ ", " ++ b ++ ")"
eqExpr (TList _ _) _ _ = "false // TODO: List equality not yet implemented"
eqExpr (TArr8 n) a b =
  let halfBits = n * 8 `div` 2
      hTy      = "u" ++ show halfBits
  in "{\n" ++
     "            let (" ++ a ++ "_hi, " ++ a ++ "_lo): (" ++ hTy ++ ", " ++ hTy ++ ") = <[u8; " ++ show n ++ "]>::into(" ++ a ++ ");\n" ++
     "            let (" ++ b ++ "_hi, " ++ b ++ "_lo): (" ++ hTy ++ ", " ++ hTy ++ ") = <[u8; " ++ show n ++ "]>::into(" ++ b ++ ");\n" ++
     "            match eq_" ++ show halfBits ++ "(" ++ a ++ "_hi, " ++ b ++ "_hi) {\n" ++
     "                true => eq_" ++ show halfBits ++ "(" ++ a ++ "_lo, " ++ b ++ "_lo),\n" ++
     "                false => false,\n" ++
     "            }\n" ++
     "        }"
eqExpr (TPair t1 t2) a b =
  let pTy = "(" ++ tyStr t1 ++ ", " ++ tyStr t2 ++ ")"
      al = a ++ "_fst"; ar = a ++ "_snd"
      bl = b ++ "_fst"; br = b ++ "_snd"
  in "{\n" ++
     "            let (" ++ al ++ ", " ++ ar ++ "): " ++ pTy ++ " = <" ++ pTy ++ ">::into(" ++ a ++ ");\n" ++
     "            let (" ++ bl ++ ", " ++ br ++ "): " ++ pTy ++ " = <" ++ pTy ++ ">::into(" ++ b ++ ");\n" ++
     "            match " ++ eqExpr t1 al bl ++ " {\n" ++
     "                true => " ++ eqExpr t2 ar br ++ ",\n" ++
     "                false => false,\n" ++
     "            }\n" ++
     "        }"
eqExpr (TEither t1 t2) a b =
  "match (" ++ a ++ ", " ++ b ++ ") {\n" ++
  "            (Left(" ++ a ++ "_i), Left(" ++ b ++ "_i)) => " ++ eqExpr t1 (a ++ "_i") (b ++ "_i") ++ ",\n" ++
  "            (Right(" ++ a ++ "_i), Right(" ++ b ++ "_i)) => " ++ eqExpr t2 (a ++ "_i") (b ++ "_i") ++ ",\n" ++
  "            _ => false,\n" ++
  "        }"

-- | Equality body for the top level of a function (4-space indent).
eqBody :: Ty -> String -> String -> String
eqBody (TU 1)      a b = "jet::eq_1(" ++ a ++ ", " ++ b ++ ")"
eqBody (TU n)      a b = "eq_" ++ show n ++ "(" ++ a ++ ", " ++ b ++ ")"
eqBody (TRef name) a b = "eq_" ++ name ++ "(" ++ a ++ ", " ++ b ++ ")"
eqBody (TList _ _) _ _ = "false // TODO: List equality not yet implemented"
eqBody (TArr8 n) a b =
  let halfBits = n * 8 `div` 2
      hTy      = "u" ++ show halfBits
  in "let (" ++ a ++ "_hi, " ++ a ++ "_lo): (" ++ hTy ++ ", " ++ hTy ++ ") = <[u8; " ++ show n ++ "]>::into(" ++ a ++ ");\n" ++
     "    let (" ++ b ++ "_hi, " ++ b ++ "_lo): (" ++ hTy ++ ", " ++ hTy ++ ") = <[u8; " ++ show n ++ "]>::into(" ++ b ++ ");\n" ++
     "    match eq_" ++ show halfBits ++ "(" ++ a ++ "_hi, " ++ b ++ "_hi) {\n" ++
     "        true => eq_" ++ show halfBits ++ "(" ++ a ++ "_lo, " ++ b ++ "_lo),\n" ++
     "        false => false,\n" ++
     "    }"
eqBody (TPair t1 t2) a b =
  let pTy = "(" ++ tyStr t1 ++ ", " ++ tyStr t2 ++ ")"
      al = a ++ "_fst"; ar = a ++ "_snd"
      bl = b ++ "_fst"; br = b ++ "_snd"
  in "let (" ++ al ++ ", " ++ ar ++ "): " ++ pTy ++ " = <" ++ pTy ++ ">::into(" ++ a ++ ");\n" ++
     "    let (" ++ bl ++ ", " ++ br ++ "): " ++ pTy ++ " = <" ++ pTy ++ ">::into(" ++ b ++ ");\n" ++
     "    match " ++ eqExpr t1 al bl ++ " {\n" ++
     "        true => " ++ eqExpr t2 ar br ++ ",\n" ++
     "        false => false,\n" ++
     "    }"
eqBody (TEither t1 t2) a b =
  "match (" ++ a ++ ", " ++ b ++ ") {\n" ++
  "        (Left(" ++ a ++ "_i), Left(" ++ b ++ "_i)) => " ++ eqExpr t1 (a ++ "_i") (b ++ "_i") ++ ",\n" ++
  "        (Right(" ++ a ++ "_i), Right(" ++ b ++ "_i)) => " ++ eqExpr t2 (a ++ "_i") (b ++ "_i") ++ ",\n" ++
  "        _ => false,\n" ++
  "    }"

genDomainEq :: String -> Ty -> String
genDomainEq name ty = block $
  if hasListType ty
    then
      [ "fn eq_" ++ name ++ "(_a: " ++ name ++ ", _b: " ++ name ++ ") -> bool {"
      , "    false // TODO: " ++ name ++ " involves List; equality not yet implemented"
      , "}"
      ]
    else
      [ "fn eq_" ++ name ++ "(a: " ++ name ++ ", b: " ++ name ++ ") -> bool {"
      , "    " ++ eqBody ty "a" "b"
      , "}"
      ]

-- | Ordered so dependencies come before dependents.
domainTypes :: [(String, Ty)]
domainTypes =
  [ ("Confidential1", TPair (TU 1) (TU 256))
  , ("Point",         TPair (TU 1) (TU 256))
  , ("Ge",            TPair (TU 256) (TU 256))
  , ("Outpoint",      TPair (TU 256) (TU 32))
  , ("Gej",           TPair (TRef "Ge") (TU 256))
  , ("Amount1",       TEither (TRef "Point") (TU 64))
  , ("Asset1",        TEither (TRef "Point") (TU 256))
  , ("Nonce",         TEither (TRef "Point") (TU 256))
  , ("TokenAmount1",  TEither (TRef "Point") (TU 64))
  , ("Distance",      TU 16)
  , ("Duration",      TU 16)
  , ("ExplicitAmount",TU 256)
  , ("ExplicitAsset", TU 256)
  , ("ExplicitNonce", TU 256)
  , ("Fe",            TU 256)
  , ("Height",        TU 32)
  , ("Lock",          TU 32)
  , ("Message",       TU 256)
  , ("Message64",     TArr8 64)
  , ("Pubkey",        TU 256)
  , ("Scalar",        TU 256)
  , ("Signature",     TArr8 64)
  , ("Time",          TU 32)
  , ("Ctx8",          TPair (TList (TU 8) 64) (TPair (TU 64) (TU 256)))
  ]

genTypesModule :: [(String, Ty)] -> String
genTypesModule types = unlines autoGenHeader ++ intercalate "\n" (map (uncurry genDomainEq) types)

-- ---------------------------------------------------------------------------
-- IO helpers
-- ---------------------------------------------------------------------------

emit :: FilePath -> String -> IO ()
emit path content = do
  writeFile path content
  putStrLn $ "  wrote " ++ path

-- ---------------------------------------------------------------------------
-- Main
-- ---------------------------------------------------------------------------

main :: IO ()
main = do
  createDirectoryIfMissing True "std/src"

  putStrLn "Generating per-type source modules..."
  mapM_ (\tc -> emit ("std/src/" ++ tn (tcBits tc) ++ ".simf") (genTypeModule tc)) allTypes

  putStrLn "Generating domain type eq functions..."
  emit "std/src/types.simf" (genTypesModule domainTypes)

  putStrLn "\nDone."
